export interface signUpRequest {
  email: string,
  password: string,
  contact: string,
  isd: string,
  company_name: string,
  company_email: string,
  gst_no: string,
  name: string,
  is_recruiter: boolean,
  is_admin: boolean,
  resume_link: string,
  company_logo: string,
  comapny_address_line1: string,
  comapny_address_line2: string,
  comapny_address_line3: string,
  country: string,
  company_size: string,
  is_company_already_exists: boolean,
  role: string
}